version: '3.8'

services:
  dayeon-mysql:
    image: mysql:8.0
    container_name: dayeon-container
    environment:
      MYSQL_DATABASE: 'dayeon'   # MySQL 데이터베이스 이름
      MYSQL_USER: 'dayeon'     # MySQL 사용자 이름
      MYSQL_PASSWORD: 'dayeon'  # MySQL 사용자 비밀번호
      MYSQL_ROOT_PASSWORD: 'tjddnr12'  # MySQL root 계정 비밀번호
    ports:
      - '3307:3306'   # 호스트와 컨테이너 간의 포트 매핑 (호스트 포트:컨테이너 포트)
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - dayeon-network   # 컨테이너들이 사용할 네트워크 정의

volumes:
  mysql_data:   # MySQL 데이터를 저장할 볼륨 정의

networks:
  dayeon-network:   # 컨테이너들이 사용할 네트워크 정의
    driver: bridge   # 사용할 네트워크 드라이버 지정
